### ISSUE TITLE
crash on visiting some gopher holes

### ISSUE THREAD

**Issue by xfnw** [telephil9/gopher#2]
gopher crashes when visiting `gopher://sdf.org/1/users/asciibene/`

![a screenshot of the gopher program crashing after attempting to visit asciibene's sdf gopher hole](https://camo.githubusercontent.com/fcacba5defab910499dea38f6ba56fd9bdb5621e665abde7e99acfb84baccf16/68747470733a2f2f76612e6675727279706c6163652e65752f316233352e706e67)

the first line of asciibene's hole is `=============================: not found`, perhaps it is crashing because of the lack of tabs?

**Comment by telephil9** [comment]
Fixed in d2dd69c
